@url = http://localhost:3030/books
# @credential = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTcxNzkwNTksInN1YiI6MX0.UNKsNsZ58eVMa34m3J0fWLy62dTT6Hd4AwUuPwr09Hk
@credential = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTcxNzkzNjMsInN1YiI6Mn0.BZR1DrIjM8zH1C_DFtpBVTg-gba8Wcvg7idGvSevzqE
###
GET {{url}}
Authorization: {{credential}}
###
POST {{url}}
Content-Type: application/json
Authorization: {{credential}}

{
  "Title" : "5",
  "Price" : 111,
  "Description" : "5",
  "Rating" : 5
}
###
GET {{url}}/3
Authorization: {{credential}}
###
PUT {{url}}/2
Content-Type: application/json
Authorization: {{credential}}

{
  "Title" : "2 1",
  "Price" : 111,
  "Description" : "2 1",
  "Rating" : 5
}
###
DELETE  {{url}}/2
Authorization: {{credential}}